# Generated by Django 4.2.5 on 2023-10-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curd', '0003_product_delete_addproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Product_Price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Product_Quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
