# Generated by Django 4.2.5 on 2023-10-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curd', '0005_rename_cat_image_category_catimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='catid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
