# Generated by Django 4.2.5 on 2023-10-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curd', '0006_category_catid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='proid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
