# Generated by Django 4.2.5 on 2023-10-09 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curd', '0007_product_proid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='catid',
        ),
        migrations.RemoveField(
            model_name='product',
            name='proid',
        ),
    ]
