# Generated by Django 4.2.5 on 2023-10-09 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curd', '0009_blogpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
