# Generated by Django 4.2.5 on 2023-10-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curd', '0011_category_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='updatecat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Name', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=200)),
                ('catimage', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
