# Generated by Django 4.2.5 on 2023-10-12 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curd', '0012_updatecat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200)),
                ('lname', models.CharField(max_length=200)),
                ('Gender', models.CharField(max_length=200)),
                ('Ride', models.CharField(max_length=200)),
                ('Emp_ID', models.CharField(max_length=200)),
                ('Des_ID', models.CharField(max_length=200)),
                ('phone', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
