# Generated by Django 4.2.5 on 2023-10-12 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curd', '0014_rename_fname_details_f_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Details',
            new_name='EmployeeDetails',
        ),
    ]
