# Generated by Django 4.2.5 on 2023-10-12 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curd', '0015_rename_details_employeedetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeedetails',
            old_name='Des_ID',
            new_name='Des',
        ),
    ]
