# Generated by Django 4.2.5 on 2023-10-13 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curd', '0016_rename_des_id_employeedetails_des'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=200)),
                ('l_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('ride', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
