# Generated by Django 4.2.5 on 2023-10-13 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curd', '0018_student_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='mobile1',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
