# Generated by Django 4.2.5 on 2023-10-16 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curd', '0021_studentform'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='studentform',
            table='studentform',
        ),
    ]
