# Generated by Django 4.2.5 on 2023-10-17 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curd', '0022_alter_studentform_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='studentform',
            table=None,
        ),
    ]
