# Generated by Django 4.2.5 on 2023-10-17 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curd', '0023_alter_studentform_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentform',
            name='mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
