# Generated by Django 4.2.5 on 2023-10-17 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curd', '0025_remove_studentform_mobile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='studentform',
        ),
    ]
