# Generated by Django 4.2.5 on 2023-10-17 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curd', '0027_studentform'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentform',
            name='mobile1',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
