# Generated by Django 4.2.5 on 2023-10-17 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curd', '0028_studentform_mobile1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentform',
            name='mobile1',
        ),
    ]
